### ISSUE TITLE
mobile view adopted design

### ISSUE THREAD

**Issue by yurii-zhukow** [HelloFax/hellosign-embedded#1]
it is highly appreciated to adopt design of front-end signing view to respect small screens.
i.e. 500x800 pixels or even smaller. need to have native zooming& sliding support leaving navigation elements at their sides.

**Comment by renderf0x** [comment]
Heya @yurii-zhukow - right now, we're optimizing for smartphone mobile screens when you use the `uXVersion: 2` parameter with `HelloSign.open`. This has been pretty heavily tested on iPhone / Android. 
Is there another type of device you had in mind?

**Comment by renderf0x** [comment]
@yurii-zhukow did you get this working with using the parameter above? Let us know if not; otherwise I'll close this.
