### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by xt0rted** [HelloFax/hellosign-embedded#10]
For anyone using TypeScript I just submitted a PR to add typings for this project to DefinitelyTyped. They're based on what's in master right now.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10522

**Comment by renderf0x** [comment]
Awesome, thanks for putting this in @xt0rted . Though we don't currently use TS internally this should be great for folks who do.

Ping back when it's merged, and we (or you via PR) can add a note in the README here about where to find those bindings.

**Comment by xt0rted** [comment]
This was added to Definitely Typed. There's a pending PR for v1.2.0 as well https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11945

**Comment by renderf0x** [comment]
Added to the readme -- thanks @xt0rted !
