### ISSUE TITLE
Uncaught TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by landerton** [HelloFax/hellosign-embedded#19]
I get this error whenever I embed a signing document.

**Comment by renderf0x** [comment]
@landerton sorry for the slow response here.

 I'd be curious what you're sending as request parameters - this shouldn't be an issue in most cases.

Please give us a shout at:
apisupport@hellosign.com
and we'll sort you out.

**Comment by leonzinger** [comment]
Hi @renderf0x,

I receive the same error. And i suspect that it causes issues further on.

First time i embed in client it shows the doc for signature and i get the error in console. But when i try to render it again after went back and forth in a single page app based on reactjs it does not render anything in the container.

here is the log after adding debug: true


first time:

`Embed Mount
embedded.js:930 Opening HelloSign embedded iFrame with the following params:
embedded.js:930 Object {skipDomainVerification: true, url: "https://app.hellosign.com/editor/embeddedSign?sign…<signatureID>&token=<token>", container: div#hellosign_embedded, uxVersion: 2, debug: true}
embedded.js:930 XWM Receive: Initialize receiver.
embedded.js:930   callback: _parentWindowCallback
embedded.js:930   sourceOrigin: https://app.hellosign.com
core.js:104  action startupAgreement:url:success @ 17:27:11.508
VM144 hellosign-embedded.LATEST.min.js:48 Domain verification has been skipped. Before requesting approval for your app, please be sure to test domain verification by setting skipDomainVerification to false.
VM140 default.js:59 Parent domain check: passed
VM144 hellosign-embedded.LATEST.min.js:48 XWM Send: Sending Message.
VM144 hellosign-embedded.LATEST.min.js:48   targetUrl: http://mydomain.dev/mypageurl
VM144 hellosign-embedded.LATEST.min.js:48   message: hello:f46bb4ecef3f10d0dfd7983c3d36e6d2
VM144 hellosign-embedded.LATEST.min.js:48 XWM Send: Message sent.
embedded.js:930 XWM Receive: Message received!
embedded.js:930   data: hello:f46bb4ecef3f10d0dfd7983c3d36e6d2
embedded.js:930   sourceOrigin: https://app.hellosign.com
embedded.js:930 XWM Send: Sending Message.
embedded.js:930   targetUrl: https://app.hellosign.com/editor/embeddedSign?signature_id=529dc1965b41fa6f…8f6eea3bb958df6a51f5231369e&user_culture=en_US&debug=true&js_version=1.2.7
embedded.js:930   message: helloback:f46bb4ecef3f10d0dfd7983c3d36e6d2
embedded.js:930 XWM Send: Message sent.
raven.js:80 Work with us: https://www.hellosign.com/info/jobs
raven.js:80 To start using the HelloSign dev tools, run app.help()
raven.js:80 XWM Receive: Initialize receiver.
raven.js:80   callback: Anonymous function
raven.js:80   sourceOrigin: *
raven.js:80 XWM Send: Sending Message.
raven.js:80   targetUrl: http://mydomain.dev/mypageurl
raven.js:80   message: initialize
raven.js:80 XWM Send: Message sent.
embedded.js:930 XWM Receive: Message received!
embedded.js:930   data: initialize
embedded.js:930   sourceOrigin: https://app.hellosign.com
embedded.js:643 Uncaught TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at _parentWindowCallback (embedded.js:643)
    at self.rmCallback (embedded.js:140)
_parentWindowCallback @ embedded.js:643
self.rmCallback @ embedded.js:140`

second time (nothing renders inside the container):

`Embed Mount
embedded.js:930 Opening HelloSign embedded iFrame with the following params:
embedded.js:930 Object {skipDomainVerification: true, url: "https://app.hellosign.com/editor/embeddedSign?sign…<signatureID>&token=<token>", container: div#hellosign_embedded, uxVersion: 2, debug: true}container: div#hellosign_embeddeddebug: trueskipDomainVerification: trueurl: "https://app.hellosign.com/editor/embeddedSign?signature_id=<signatureID>&token=<token>"uxVersion: 2__proto__: Object
embedded.js:930 XWM Receive: Initialize receiver.
embedded.js:930   callback: _parentWindowCallback
embedded.js:930   sourceOrigin: https://app.hellosign.com`

**Comment by cmpaul** [comment]
@leonzinger When you say you "try to render it again," what do you mean? Are you requesting a new `sign_url` and calling `HelloSign.open()` with it?
