### ISSUE TITLE
Close button missing for embedded requesting and template windows

### ISSUE THREAD

**Issue by ghost** [HelloFax/hellosign-embedded#7]
This change prevents the close button from appearing for embedded requesting and templates:

https://github.com/HelloFax/hellosign-embedded/commit/5c60a90e918c40e9f18f0efca7f0c2f51152ff49#diff-a5b731da43f7671d41e300f62162770fR542

I'm going to add another check for this to only check this for embedded signing.

**Comment by renderf0x** [comment]
Thanks for the PR! Looks like this was merged, so I'm going to close this issue.

**Comment by arjshiv** [comment]
@renderf0x this seems to be happening with `uxVersion: 2`, not sure why. 

Our settings look like this:

```js
HelloSign.open({ 
    url: url, 
    allowCancel: true, 
    messageListener: function(eventData) {
      ...
    }
   });
```

When we add `uxVersion: 1` to the `params`, we see the old close button working. 

For further context, we're not using any special CSS, but our app is built with React and Redux, and we're using the `npm` version of this code by importing it into our codebase.

Happy to provide further details.
