### ISSUE TITLE
Error: "init is not a function" with 1.6.0

### ISSUE THREAD

**Issue by sturnquest** [HelloFax/hellosign-embedded#71]
I'm getting an error on init with version 1.6.0.

Steps to reproduce:

1. `git clone git@github.com:HelloFax/hellosign-embedded.git`
2. `cd hellosign-embedded/`
3. `shopt -s extglob` 
4. `rm -rf !(demo)` (remove all sub-directories except demo)
5. `cd demo/`
6. change the `hellosign-embedded` entry in `package.json` to read: `"hellosign-embedded": "^1.6.0"`
7. `rm package-lock.json`
8. `npm install`
9.  `npm start`
10. open `http://localhost:3000/` in a browser
11. enter your api key and client id
12. click "open"

Result:

You'll see the following console log message...

```
Uncaught (in promise) TypeError: hellosign_embedded__WEBPACK_IMPORTED_MODULE_0___default.a.init is not a function
    at openRequest (index.js:69)
    at index.js:49
```

If I follow the exact steps above but use `"hellosign-embedded": "1.5.2"`then it works.

**Comment by nathanbuchar** [comment]
Looking into this, thanks!
