### ISSUE TITLE
Setting default configuration values

### ISSUE THREAD

**Issue by xt0rted** [HelloFax/hellosign-embedded#9]
Is it safe to set default settings values such as `HelloSign.skipDomainVerification = true;`? I'd like to remove this from the `.open()` function so I can manage it in one spot instead of every spot I open a signing.

The other setting I'd like to use my own default for is `HelloSign.DEFAULT_UX_VERSION = 2;`.

It'd be useful if default settings could be passed to the `.init()` function so it's well documented as to what can be changed.

**Comment by renderf0x** [comment]
@xt0rted There shouldn't be any issues with doing that; so long as the HelloSign library is in window scope it should retain your settings.

I don't know if we've yet seen enough cases where folks wanted to do what you're describing to prioritize creating a handler for them in the `init` function, but we'd defo be open to a pull request if you have one.

re: the `HelloSign.DEFAULT_UX_VERSION` - we do intend on changing this to v2 soon, but you may actually want to be setting `HelloSign.uxVersion` instead, as we do some comparison logic with the `DEFAULT_UX_VERSION` value to determine if we need to prepare for the v1 experience.
I'd recommend against changing that (use the param above instead).
